volumes:
  db_data:

services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '${DOCKER_POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    image: azizramdan/bearmentor-upperwear-app
    restart: always
    ports:
      - '${DOCKER_APP_PORT}:3000'
